name = "olympiad"
compatibility_date = "2025-09-29"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]